const groceryItems = [
  {
    item: "Apples",
    price: 1.5,
    category: "Fruits",
    image: "/apple.png",
  },
  {
    item: "Bananas",
    price: 0.75,
    category: "Fruits",
    image: "../public/BANANA.png",
  },
  {
    item: "Bread",
    price: 2.0,
    category: "Bakery",
    image: "../public/bread.png",
  },
  {
    item: "Milk",
    price: 3.5,
    category: "Dairy",
    image: "../public/milk.png",
  },
  {
    item: "Eggs",
    price: 2.25,
    category: "Dairy",
    image: "../public/eggs.png",
  },
  {
    item: "Chicken Breast",
    price: 5.99,
    category: "Meat",
    image: "../public/chickenbreast.png",
  },
  {
    item: "Broccoli",
    price: 1.2,
    category: "Vegetables",
    image: "../public/Broccoli.png",
  },
  {
    item: "Rice",
    price: 1.8,
    category: "Grains",
    image: "../public/rice.png",
  },
  {
    item: "Pasta",
    price: 1.0,
    category: "Grains",
    image: "../public/pasta.png",
  },
  {
    item: "Cheese",
    price: 4.5,
    category: "Dairy",
    image: "../public/Cheese.png",
  },
  {
    item: "Oranges",
    price: 1.0,
    category: "Fruits",
    image: "../public/Oranges.png",
  },
  {
    item: "Tomatoes",
    price: 1.3,
    category: "Vegetables",
    image: "../public/Tomato.png",
  },
  {
    item: "Carrots",
    price: 0.9,
    category: "Vegetables",
    image: "../public/carrot.png",
  },
  {
    item: "Potatoes",
    price: 1.0,
    category: "Vegetables",
    image: "../public/potatoes.png",
  },
  {
    item: "Spinach",
    price: 2.0,
    category: "Vegetables",
    image: "../public/spinach.png",
  },
  {
    item: "Ground Beef",
    price: 6.5,
    category: "Meat",
    image: "../public/goundbeef.png",
  },
  {
    item: "Yogurt",
    price: 0.8,
    category: "Dairy",
    image: "../public/yogurt.png",
  },
  {
    item: "Peanut Butter",
    price: 3.0,
    category: "Pantry",
    image: "../public/peanutbutter.png",
  },
  {
    item: "Honey",
    price: 4.0,
    category: "Pantry",
    image: "../public/honey.png",
  },
  {
    item: "Cereal",
    price: 3.5,
    category: "Pantry",
    image: "../public/cereal.png",
  },
];
export { groceryItems };
