const groceryItems = [
  {
    item: "Apples",
    price: 1.5,
    category: "Fruits",
    image: "../JS/productimgs/apple.png",
  },
  {
    item: "Bananas",
    price: 0.75,
    category: "Fruits",
    image: "../JS/productimgs/BANANA.png",
  },
  {
    item: "Bread",
    price: 2.0,
    category: "Bakery",
    image: "../JS/productimgs/bread.png",
  },
  {
    item: "Milk",
    price: 3.5,
    category: "Dairy",
    image: "../JS/productimgs/milk.png",
  },
  {
    item: "Eggs",
    price: 2.25,
    category: "Dairy",
    image: "../JS/productimgs/eggs.png",
  },
  {
    item: "Chicken Breast",
    price: 5.99,
    category: "Meat",
    image: "../JS/productimgs/chickenbreast.png",
  },
  {
    item: "Broccoli",
    price: 1.2,
    category: "Vegetables",
    image: "../JS/productimgs/Broccoli.png",
  },
  {
    item: "Rice",
    price: 1.8,
    category: "Grains",
    image: "../JS/productimgs/rice.png",
  },
  {
    item: "Pasta",
    price: 1.0,
    category: "Grains",
    image: "../JS/productimgs/pasta.png",
  },
  {
    item: "Cheese",
    price: 4.5,
    category: "Dairy",
    image: "../JS/productimgs/Cheese.png",
  },
  {
    item: "Oranges",
    price: 1.0,
    category: "Fruits",
    image: "../JS/productimgs/Oranges.png",
  },
  {
    item: "Tomatoes",
    price: 1.3,
    category: "Vegetables",
    image: "../JS/productimgs/Tomato.png",
  },
  {
    item: "Carrots",
    price: 0.9,
    category: "Vegetables",
    image: "../JS/productimgs/carrot.png",
  },
  {
    item: "Potatoes",
    price: 1.0,
    category: "Vegetables",
    image: "../JS/productimgs/potatoes.png",
  },
  {
    item: "Spinach",
    price: 2.0,
    category: "Vegetables",
    image: "../JS/productimgs/spinach.png",
  },
  {
    item: "Ground Beef",
    price: 6.5,
    category: "Meat",
    image: "../JS/productimgs/goundbeef.png",
  },
  {
    item: "Yogurt",
    price: 0.8,
    category: "Dairy",
    image: "../JS/productimgs/yogurt.png",
  },
  {
    item: "Peanut Butter",
    price: 3.0,
    category: "Pantry",
    image: "../JS/productimgs/peanutbutter.png",
  },
  {
    item: "Honey",
    price: 4.0,
    category: "Pantry",
    image: "../JS/productimgs/honey.png",
  },
  {
    item: "Cereal",
    price: 3.5,
    category: "Pantry",
    image: "../JS/productimgs/cereal.png",
  },
];
export { groceryItems };
