const groceryItems = [
  {
    item: "Apples",
    price: 1.5,
    category: "Fruits",
    image: "../apple.png",
  },
  {
    item: "Bananas",
    price: 0.75,
    category: "Fruits",
    image: "../BANANA.png",
  },
  {
    item: "Bread",
    price: 2.0,
    category: "Bakery",
    image: "../bread.png",
  },
  {
    item: "Milk",
    price: 3.5,
    category: "Dairy",
    image: "../milk.png",
  },
  {
    item: "Eggs",
    price: 2.25,
    category: "Dairy",
    image: "../eggs.png",
  },
  {
    item: "Chicken Breast",
    price: 5.99,
    category: "Meat",
    image: "../chickenbreast.png",
  },
  {
    item: "Broccoli",
    price: 1.2,
    category: "Vegetables",
    image: "../Broccoli.png",
  },
  {
    item: "Rice",
    price: 1.8,
    category: "Grains",
    image: "../rice.png",
  },
  {
    item: "Pasta",
    price: 1.0,
    category: "Grains",
    image: "../pasta.png",
  },
  {
    item: "Cheese",
    price: 4.5,
    category: "Dairy",
    image: "../Cheese.png",
  },
  {
    item: "Oranges",
    price: 1.0,
    category: "Fruits",
    image: "../Oranges.png",
  },
  {
    item: "Tomatoes",
    price: 1.3,
    category: "Vegetables",
    image: "../Tomato.png",
  },
  {
    item: "Carrots",
    price: 0.9,
    category: "Vegetables",
    image: "../carrot.png",
  },
  {
    item: "Potatoes",
    price: 1.0,
    category: "Vegetables",
    image: "../potatoes.png",
  },
  {
    item: "Spinach",
    price: 2.0,
    category: "Vegetables",
    image: "../spinach.png",
  },
  {
    item: "Ground Beef",
    price: 6.5,
    category: "Meat",
    image: "../goundbeef.png",
  },
  {
    item: "Yogurt",
    price: 0.8,
    category: "Dairy",
    image: "../yogurt.png",
  },
  {
    item: "Peanut Butter",
    price: 3.0,
    category: "Pantry",
    image: "../peanutbutter.png",
  },
  {
    item: "Honey",
    price: 4.0,
    category: "Pantry",
    image: "../honey.png",
  },
  {
    item: "Cereal",
    price: 3.5,
    category: "Pantry",
    image: "../cereal.png",
  },
];
export { groceryItems };
